repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: ffeafd11ff2cc846434edec9e63e6a66ac0ab9ab
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
