repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 66a2db0e6f225450e9d0b1ea21f988435c0b524f
    hooks:
      - id: check-keywords
        args: ["--keywords", "", "--exclude-files", ""]
