repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 67ae73f34637a8a6cf51fefcba3a898a1a96d315
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
