repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: b51bc47d697183a81198d28b02a831558840c0e6
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
