repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 0ad6fae243dcd064f6c3cc169466dca476fb4ad0
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
