repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 75c1bf8f23a9bdc2ace766374288e9b60dd53ea7
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
