repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 9353f985fa409490a9aeacf0df6df13f3a81d13b
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
