repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: 69e4b6d2c8fb864045902cea95a24e6fae5261e3
    hooks:
      - id: check-keywords
        args: ["--keywords", "", "--exclude-files", ""]
