repos:
  - repo: https://github.com/AliYmn/pre-commit-keyword-checker
    rev: d2a57eaf3535de79bc14131d80b9197f51585011
    hooks:
      - id: check-keywords
        args: ["--keywords", "--exclude-files"]
